jaffle_shop:
  outputs:
    dev:
      dataset: jaffle_shop
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/airflow/.dbt/dbt-user-creds.json
      location: EU
      method: service-account
      priority: interactive
      project: cabk-406111
      threads: 1
      type: bigquery
  target: dev